services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://urlshortener:dockerpassword@postgres:5432/url_shortener
      PORT: 3000
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c 'node_modules/.bin/prisma db migrate &&
      npm start'

  postgres:
    image: postgres:18
    container_name: url-shortener-postgres
    environment:
      POSTGRES_USER: urlshortener
      POSTGRES_PASSWORD: dockerpassword
      POSTGRES_DB: url_shortener
    volumes:
      - url_shortener_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U urlshortener -d url_shortener"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  url_shortener_data: